# Generated by Django 4.1.2 on 2022-11-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=234, max_length=40),
            preserve_default=False,
        ),
    ]
